[package]
name = "spotify_web_playback_SDK"
version = "0.1.0"
edition = "2021"

[dependencies]
web-sys = "0.3"
js-sys = "0.3"
wasm-bindgen-futures = "0.4.42"
nestify = "0.3.3"
serde-wasm-bindgen = "=0.6.5"
serde = { version = "1.0", features = ["derive"] }