[package]
name = "rust_spotify_web_playback_sdk_macro"
edition = "2021"
publish = true
version = "0.2.2"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0"
quote = "1.0"
syn = { version = "1.0", features = ["full"] }
